name: Python Script Every 5 Minutes

on:
  schedule:
    - cron: '*/5 * * * *'  # Runs every 5 minutes
  workflow_dispatch:

jobs:
  run_python_script:
    runs-on: ubuntu-latest
    environment: prod
    env:
      SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
      SENDER_PASSWORD: ${{ secrets.SENDER_PASSWORD }}
      RECIPIENT_EMAIL: ${{ secrets.RECIPIENT_EMAIL }}
      EMAIL_SUBJECT: ${{ secrets.EMAIL_SUBJECT }}
      EMAIL_BODY: ${{ secrets.EMAIL_BODY }}
      TEST: "TEST_VALUE"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Run Python script
        run: echo "$SENDER_EMAIL"
